name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check-format:
    name: Check format using flutter format
    runs-on: ubuntu-latest
    container: cirrusci/flutter:stable

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check format
        run: dart format --set-exit-if-changed .

  lint:
    name: Check lints
    runs-on: ubuntu-latest
    container: cirrusci/flutter:stable

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get dependencies 
        run: flutter pub get
      - name: Lint using flutter analyze
        run: flutter analyze
        